/**
 * @type {import('@react-native-community/cli-types').UserDependencyConfig}
 */
module.exports = {
  dependency: {
    platforms: {
      android: {
        // Codegen output is generated by bob build and shipped in the package
        cmakeListsPath: 'generated/jni/CMakeLists.txt',
      },
    },
  },
}
