/**
 * @type {import('@react-native-community/cli-types').UserDependencyConfig}
 */
module.exports = {
  dependency: {
    platforms: {
      android: {
        // Codegen output is generated by bob build and shipped in the package
        cmakeListsPath: 'generated/jni/CMakeLists.txt',
        // The C++ module (cpp/android/ZeroconfAndroidModule), built by android/CMakeLists.txt
        cxxModuleCMakeListsModuleName: 'react-native-zeroconf',
        cxxModuleCMakeListsPath: 'CMakeLists.txt',
        cxxModuleHeaderName: 'ZeroconfAndroidModule',
      },
    },
  },
}
